version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - monitor_net

  cacti-db:
    image: mariadb:10.5
    container_name: cacti-db
    restart: always
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_connections=200
      - --max_heap_table_size=128M
      - --max_allowed_packet=32M
      - --tmp_table_size=128M
      - --join_buffer_size=250M
      - --innodb_buffer_pool_size=2G
      - --innodb_doublewrite=ON
      - --innodb_flush_log_at_timeout=3
      - --innodb_read_io_threads=32
      - --innodb_write_io_threads=16
      - --innodb_buffer_pool_instances=9
      - --innodb_file_format=Barracuda
      - --innodb_large_prefix=1
      - --innodb_io_capacity=5000
      - --innodb_io_capacity_max=10000
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./cacti/db:/var/lib/mysql
    networks:
      - monitor_net

  cacti:
    image: smcline06/cacti
    container_name: cacti
    restart: always
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: cacti-db
      DB_PORT: 3306
      DB_ROOT_PASS: ${MYSQL_ROOT_PASSWORD}
      INITIALIZE_DB: 1
      TZ: ${TZ}
    depends_on:
      - cacti-db
    volumes:
      - ./cacti/data:/cacti
      - ./cacti/spine:/spine
      - ./cacti/backups:/backups
    expose:
      - "80"
    networks:
      - monitor_net

  nagios:
    image: jasonrivers/nagios:latest
    container_name: nagios
    restart: always
    volumes:
      - ./nagios/etc:/opt/nagios/etc
    expose:
      - "80"
    networks:
      - monitor_net

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    environment:
      - TZ=${TZ}
    volumes:
      - ./uptime-kuma:/app/data
    expose:
      - "3001"
    networks:
      - monitor_net

networks:
  monitor_net:
    driver: bridge
